export const OB_STEPS = [
  {
    id: "niveau",
    title: "Tu es en quelle classe ?",
    multi: false,
    choices: [
      { sym: "◎", label: "Seconde" },
      { sym: "◎", label: "Première" },
      { sym: "◎", label: "Terminale" },
      { sym: "◎", label: "Post-bac" },
    ],
  },
  {
    id: "matieres",
    title: "Quelles matières tu aimes ?",
    hint: "Choix multiple",
    multi: true,
    choices: [
      { sym: "▲", label: "Maths" },
      { sym: "▲", label: "Sciences" },
      { sym: "▲", label: "Informatique" },
      { sym: "▲", label: "Lettres" },
      { sym: "▲", label: "Langues" },
      { sym: "▲", label: "Arts" },
      { sym: "▲", label: "Eco & Gestion" },
      { sym: "▲", label: "Sport" },
      { sym: "▲", label: "Histoire-Geo" },
    ],
  },
  {
    id: "style",
    title: "Comment tu travailles ?",
    hint: "Choix multiple",
    multi: true,
    wide: true,
    choices: [
      { sym: "→", label: "Plutot seul", sub: "Je me concentre mieux seul" },
      { sym: "→", label: "En equipe", sub: "J'aime collaborer" },
      { sym: "→", label: "Creatif", sub: "J'aime inventer, concevoir" },
      { sym: "→", label: "Analytique", sub: "J'aime structurer, comprendre" },
      { sym: "→", label: "Concret", sub: "J'aime faire, construire" },
      { sym: "→", label: "Conceptuel", sub: "J'aime les idees abstraites" },
    ],
  },
  {
    id: "duree",
    title: "Duree d'etudes envisagee ?",
    multi: false,
    wide: true,
    choices: [
      { sym: "◆", label: "Courtes — Bac+2/3", sub: "BTS, BUT, Licence Pro" },
      { sym: "◆", label: "Moyennes — Bac+3/4", sub: "Licence, Bachelor" },
      { sym: "◆", label: "Longues — Bac+5 et +", sub: "Master, Grande ecole" },
      { sym: "◆", label: "Je ne sais pas encore", sub: "On verra selon les options" },
    ],
  },
  {
    id: "domaines",
    title: "Tu as des domaines en tete ?",
    hint: "Choix multiple",
    multi: true,
    hasFree: true,
    choices: [
      { sym: "◉", label: "Informatique & Tech" },
      { sym: "◉", label: "Sante & Medecine" },
      { sym: "◉", label: "Droit & Justice" },
      { sym: "◉", label: "Finance & Commerce" },
      { sym: "◉", label: "Art & Design" },
      { sym: "◉", label: "Sciences" },
      { sym: "◉", label: "Communication" },
      { sym: "◉", label: "Pas encore d'idee", sub: "Le matching m'aidera" },
    ],
  },
];
